// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}


function createMockSupabaseClient() {
  const createMockQuery = () => {
    const result = { data: [] as any, error: null };
    const callable = () => createMockQuery();
    return new Proxy(callable, {
      get(_, prop) {
        if (prop === 'maybeSingle' || prop === 'single') {
          return async () => ({ data: null, error: null });
        }
        if (prop === 'then') {
          return (resolve: any) => resolve(result);
        }
        return createMockQuery();
      },
    });
  };

  const mockAuth = new Proxy({} as any, {
    get(_, prop) {
      if (prop === 'getUser') {
        return async () => ({ data: { user: null }, error: null });
      }
      if (prop === 'signInWithPassword') {
        return async () => ({ data: { user: null, session: null }, error: { message: 'Mock auth' } });
      }
      if (prop === 'signUp') {
        return async () => ({ data: { user: null, session: null }, error: { message: 'Mock auth' } });
      }
      return mockAuth;
    },
  });

  return {
    from: (...args: any[]) => createMockQuery(),
    auth: mockAuth,
    channel: () => ({
      on: () => ({ subscribe: () => ({}) }),
    }),
    removeChannel: () => Promise.resolve(),
  } as unknown as ReturnType<typeof createClient<Database>>;
}


function createSupabaseClient() {
  const SUPABASE_URL = process.env['NEXT_PUBLIC_SUPABASE_URL'] || process.env['SUPABASE_URL'];
  const SUPABASE_PUBLISHABLE_KEY = process.env['NEXT_PUBLIC_SUPABASE_ANON_KEY'] || process.env['SUPABASE_PUBLISHABLE_KEY'];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    const missing = [
      ...(!SUPABASE_URL ? ['NEXT_PUBLIC_SUPABASE_URL or SUPABASE_URL'] : []),
      ...(!SUPABASE_PUBLISHABLE_KEY ? ['NEXT_PUBLIC_SUPABASE_ANON_KEY or SUPABASE_PUBLISHABLE_KEY'] : []),
    ];
    const message = `Missing Supabase environment variable(s): ${missing.join(', ')}. Set them in your .env file.`;
    console.error(`[Supabase] ${message}`);

    return createMockSupabaseClient();
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: typeof window !== 'undefined' ? localStorage : undefined,
      persistSession: true,
      autoRefreshToken: true,
    }
  });
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    return Reflect.get(_supabase, prop, receiver);
  },
});

